version: "3.8"

services:
  backend:
     image: node:14-alpine
     command: sh -c "npm i && npm start"
     ports:
      - 9000:9000
     working_dir: /backend
     volumes:
       - ./backend:/backend


  frontend:
     image: node:14-alpine
     command: sh -c "npm i && npm start"
     ports:
       - 8000:8000
     working_dir: /frontend
     volumes:
       - ./frontend:/frontend


